### ISSUE TITLE
Option to selectively disable sorting for an entry in an array or whole array

### ISSUE THREAD

**Issue by paddyroddy** [pappasam/toml-sort#43]
It would be great to have the ability to selectively disable sorting for an array (via a comment or a flag in the config). I think the sorting feature is great, but I can only solve this by disabling it for all files, like in #37.
```
[tool.tomlsort]
all = false
sort_inline_arrays = false
```

For example, with [Coverage](https://coverage.readthedocs.io) for the following to work `src` must appear before the `.tox` line, but sorting will change it.
```
[tool.coverage]
paths.source = [
    "src",
    ".tox*/*/lib/python*/site-packages",
]
```

**Comment by KyleKing** [comment]
I like the idea of a comment and I'm planning on working on #42. Using a configuration would be hard to specify what the rule applies to.

What do you think of using `# toml-sort: pin` for the comment?

With the comment, you could write:

```toml
[tool.coverage]
paths.source = [
    "src",  # toml-sort: pin
    ".tox*/*/lib/python*/site-packages",
]
```

And in my case:

```toml
[tool.poetry.dependencies]
python = "^3.11"  # toml-sort: pin
antigravity = "^0.1"
```

---

The relative order of pins to eachother would be preserved and they would always be moved to the top:

```toml
[tool.coverage]
paths.source = [
    ".tox*/*/lib/python*/site-packages",
    "src",  # toml-sort: pin
	"another",  # toml-sort: pin
]
```

Where `another` is pinned *after* `src`, so that after sorting, this would be the end result:


```toml
[tool.coverage]
paths.source = [
    "src",  # toml-sort: pin
	"another",  # toml-sort: pin
    ".tox*/*/lib/python*/site-packages",
]
```

vs. without the comments:

```toml
[tool.coverage]
paths.source = [
    ".tox*/*/lib/python*/site-packages",
	"another",
    "src",
]
```

---

To selectively ignore an entire array, maybe we could add another type of comment code:

```toml
[tool.coverage]
paths.source = [  # toml-sort: no-sort
    ".tox*/*/lib/python*/site-packages",
    "src",
	"another",
]
```

--

Any opinions on this approach? Is this the desired behavior?

**Comment by jonathangreen** [comment]
I've thought about doing something like this by allowing config overrides per key.

Something like this might work for config file syntax:

```toml
[tool.tomlsort.overrides]
tool.coverage.sort_inline_arrays = false
```

Where `sort_inline_arrays` could be any of the configuration options currently available.

I think that would provide a lot of flexibility when specific sections need different sort options.

**Comment by paddyroddy** [comment]
> I like the idea of a comment and I'm planning on working on #42. Using a configuration item seems like it would be hard to specify what the rule applies to, while a comment is very clear and a well established pattern for Python tools (flake8, mypy, etc.).
> 
> What do you think of using `# toml-sort: pin` for the comment?
> 
> With the comment, you could write:
> 
> ```toml
> [tool.coverage]
> paths.source = [
>     "src",  # toml-sort: pin
>     ".tox*/*/lib/python*/site-packages",
> ]
> ```
> 
> And in my case:
> 
> ```toml
> [tool.poetry.dependencies]
> python = "^3.11"  # toml-sort: pin
> antigravity = "^0.1"
> ```
> 
> The relative order of pins to eachother would be preserved and they would always be moved to the top:
> 
> ```toml
> [tool.coverage]
> paths.source = [
>     ".tox*/*/lib/python*/site-packages",
>     "src",  # toml-sort: pin
> 	"another",  # toml-sort: pin
> ]
> ```
> 
> Where `another` is pinned _after_ `src`, so that after sorting, this would be the end result:
> 
> ```toml
> [tool.coverage]
> paths.source = [
>     "src",  # toml-sort: pin
> 	"another",  # toml-sort: pin
>     ".tox*/*/lib/python*/site-packages",
> ]
> ```
> 
> vs. without the comments:
> 
> ```toml
> [tool.coverage]
> paths.source = [
>     ".tox*/*/lib/python*/site-packages",
> 	"another",
>     "src",
> ]
> ```
> 
> To selectively ignore an entire array, maybe we could add another type of comment code:
> 
> ```toml
> [tool.coverage]
> paths.source = [  # toml-sort: no-sort
>     ".tox*/*/lib/python*/site-packages",
>     "src",
> 	"another",
> ]
> ```
> 
> **Any opinions on this approach? Is this the desired behavior?**

This looks like a great solution!

**Comment by paddyroddy** [comment]
> I've thought about doing something like this by allowing config overrides either per key or per table.
> 
> Something like this might work for config file syntax:
> 
> ```toml
> [tool.tomlsort.overrides]
> tool.coverage.sort_inline_arrays = false
> ```
> 
> Where `sort_inline_arrays` could be any of the configuration options currently available.
> 
> I think that would provide a lot of flexibility when specific tables need different sort options.

That would be really cool, but I sense a bit harder to implement than the comment option? I guess in my case I'd really be looking for `tool.coverage.paths.source.sort_inline_arrays = false` but that might be even harder to do.

**Comment by KyleKing** [comment]
I almost think we might want both options:

- Config: one source of truth for how files should be sorted, but requires a configuration file because specifying by CLI would be cumbersome
- Comments: easy to specify per file, but repetitive, especially for defaults like `tool.poetry.dependencies.python` and will stop working if the array is moved inline

Maybe the new logic in `toml-sort` could:

1. Scan the file for comments
2. Merge the comment overrides with the config overrides
3. Sort
4. Apply the overrides

Maybe we could borrow the concept of `known_first_party` from `isort` with `sort_first` and expand the `sort_inline_arrays` to be a more general `no_sort`. If so, the configuration file could look something like:

```toml
[tool.tomlsort.overrides]
no_sort = ["tool.coverage.paths.source"]

[tool.tomlsort.overrides.sort_first]
tool.poetry.dependencies = ["python"]
```

The benefit of a more general `no_sort` is that it could also apply to tables. For example, if you didn't want the poetry dependencies to be sorted at all (maybe you already use [`poetry-sort` plugin](https://pypi.org/project/poetry-sort))

```sh
[tool.tomlsort.overrides]
no_sort = ["tool.poetry.dependencies"]
```

And with `sort_first`, you could also specify multiple ordered values:

```sh
[tool.tomlsort.sort_first]
tool.coverage.paths.source = ["src", "another"]
```

**Comment by paddyroddy** [comment]
My particular use case can be solved by:
```
[tool.tomlsort]
all = true
overrides."tool.coverage.paths.source".inline_arrays = false
```
😁 cheers!

**Comment by sudoforge** [comment]
i... am sorry to revisit this so late, but i think it is **absolutely necessary** to be able to use a comment to ignore given rules for a symbol. this is an extremely common feature amongst linters and formatters for a reason: keeping it close to code makes it easy to manage.
